n_experiments: 12
output_dir: "results_july30_non_umi/collection4/"
input_dir: "data/experimental/collection4/"
seed: 42
data_generation:
  experimental: True
  method: "experimental"
  n_samples: 22000
  default_model_name: "humanTRB"
  input_columns: ["junction_aa", "v_call", "j_call", "locus"]
models:
    - name: "pwm"
      config: "configs/generative_models/PWM.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 22000
    - name: "sonnia"
      config: "configs/generative_models/SoNNia.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 22000
    - name: "vae"
      config: "configs/generative_models/SimpleVAE.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 22000
    - name: "lstm"
      config: "configs/generative_models/SimpleLSTM.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 22000
analyses:
  - - name: "memorization"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 45
    - name: "reduced_dimensionality"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
    - name: "diversity"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 45
    - name: "phenotype"
      model_names: ["pwm"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: ["sonnia"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: [ "vae" ]
      default_model_name: "humanTRB"
    - name: "network"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "train"
      n_subsets: 45
    - name: "network"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "test"
      n_subsets: 45
    - name: "precision_recall"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 45
