n_experiments: 11
output_dir: "RESULTS_NOV12/TCR"
input_dir: "data/experimental/collectionA"
seed: 42

sampling:
  - model_name: "SoNNia_overlap"
    experiment_names: ["exp_0", "exp_1", "exp_2", "exp_3", "exp_4", "exp_5", "exp_6", "exp_7", "exp_8", "exp_9", "exp_10"]
    immuneml_config: "configs/pipelines/experimental_sampling_immuneml.yaml"
    n_samples: 100000
  - model_name: "SoNNia_kmer"
    experiment_names: ["exp_0", "exp_1", "exp_2", "exp_3", "exp_4", "exp_5", "exp_6", "exp_7", "exp_8", "exp_9", "exp_10"]
    immuneml_config: "configs/pipelines/experimental_sampling_immuneml.yaml"
    n_samples: 100000
