n_experiments: 7
output_dir: "RESULTS_NOV12/BCR"
input_dir: "data/experimental/collectionB"
seed: 42

analyses:
#    - name: "reduced_dimensionality"
#      model_names: [ "PWM", "VAE_overlap", "VAE_kmer", "SoNNia_overlap", "SoNNia_kmer", "Akbar_overlap", "Akbar_kmer", "Saka_overlap", "Saka_kmer", "ProGen_overlap", "ProGen_kmer" ]
#      default_model_name: "humanIGH"
#      reference_data: [ "train", "test" ]
#      n_subsets: 6
#      subfolder_name: "all models"
#      receptor_type: "BCR"
#    - name: "memorization"
#      model_names: [ "PWM", "VAE_overlap", "VAE_kmer", "SoNNia_overlap", "SoNNia_kmer", "Akbar_overlap", "Akbar_kmer", "Saka_overlap", "Saka_kmer", "ProGen_overlap", "ProGen_kmer" ]
#      default_model_name: "humanIGH"
#      reference_data: [ "train", "test" ]
#      n_subsets: 6
#      allowed_mismatches: 0
#      indels: False
#      deduplicate: False
#      subfolder_name: "all models"
#      receptor_type: "BCR"
#    - name: "network"
#      model_names: [ "PWM", "VAE_overlap", "VAE_kmer", "SoNNia_overlap", "SoNNia_kmer", "Akbar_overlap", "Akbar_kmer", "Saka_overlap", "Saka_kmer", "ProGen_overlap", "ProGen_kmer" ]
#      default_model_name: "humanIGH"
#      reference_data: [ "train", "test" ]
#      n_subsets: 6
#      allowed_mismatches: 1
#      indels: True
#      subfolder_name: "all models"
#      receptor_type: "BCR"
#    - name: "precision_recall"
#      model_names: [ "PWM", "VAE_overlap", "VAE_kmer", "SoNNia_overlap", "SoNNia_kmer", "Akbar_overlap", "Akbar_kmer", "Saka_overlap", "Saka_kmer", "ProGen_overlap", "ProGen_kmer" ]
#      default_model_name: "humanIGH"
#      reference_data: [ "train", "test" ]
#      n_subsets: 6
#      allowed_mismatches: 0
#      indels: False
#      deduplicate: False
#      subfolder_name: "all models with distance 0"
#      receptor_type: "BCR"
#    - name: "precision_recall"
#      model_names: [ "PWM", "VAE_overlap", "VAE_kmer", "SoNNia_overlap", "SoNNia_kmer", "Akbar_overlap", "Akbar_kmer", "Saka_overlap", "Saka_kmer", "ProGen_overlap", "ProGen_kmer" ]
#      default_model_name: "humanIGH"
#      reference_data: [ "train", "test" ]
#      n_subsets: 6
#      allowed_mismatches: 1
#      indels: True
#      deduplicate: False
#      subfolder_name: "all models with distance 1"
#      receptor_type: "BCR"
#    - name: "diversity"
#      model_names: [ "PWM", "VAE_overlap", "VAE_kmer", "SoNNia_overlap", "SoNNia_kmer", "Akbar_overlap", "Akbar_kmer", "Saka_overlap", "Saka_kmer", "ProGen_overlap", "ProGen_kmer" ]
#      default_model_name: "humanIGH"
#      reference_data: [ "train", "test" ]
#      n_subsets: 6
#      subfolder_name: "all models"
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "PWM" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "PWM"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "VAE_overlap" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "VAE_overlap"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "VAE_kmer" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "VAE_kmer"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "SoNNia_overlap" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "SoNNia_overlap"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "SoNNia_kmer" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "SoNNia_kmer"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "Akbar_overlap" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "Akbar_overlap"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "Akbar_kmer" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "Akbar_kmer"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "Saka_overlap" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "Saka_overlap"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "Saka_kmer" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "Saka_kmer"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "ProGen_overlap" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "ProGen_overlap"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
#    - name: "phenotype"
#      model_names: [ "train" ]
#      default_model_name: "humanIGH"
#      subfolder_name: "train"
#      allowed_mismatches: 0
#      indels: False
#      receptor_type: "BCR"
    - name: "innovation"
      model_names: [ "PWM", "VAE_overlap", "VAE_kmer", "SoNNia_overlap", "SoNNia_kmer", "Akbar_overlap", "Akbar_kmer", "Saka_overlap", "Saka_kmer", "ProGen_overlap", "ProGen_kmer" ]
      default_model_name: "humanIGH"
      allowed_mismatches: 0
      indels: False
      subfolder_name: "all models"
      receptor_type: "BCR"
