n_experiments: 11
output_dir: "RESULTS_NOV12/TCR"
input_dir: "data/experimental/collectionA"
seed: 42

#data_generation:
#  experimental: True
#  method: "experimental"
#  n_samples: 21500
#  default_model_name: "humanTRB"
#  input_columns: ["junction_aa", "v_call", "j_call", "locus"]

models:
    - name: "Saka_overlap"
      immuneml_model_config: "configs/generative_models/TCR/Saka/S_29.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 21500
    - name: "Saka_kmer"
      immuneml_model_config: "configs/generative_models/TCR/Saka/S_19.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 21500

analyses:
    - name: "reduced_dimensionality"
      model_names: [ "Saka_overlap", "Saka_kmer" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      subfolder_name: "all Saka models"
    - name: "memorization"
      model_names: [ "Saka_overlap", "Saka_kmer" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 6
      allowed_mismatches: 0
      indels: False
      subfolder_name: "all Saka models dist 0"
    - name: "memorization"
      model_names: [ "Saka_overlap", "Saka_kmer" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 6
      allowed_mismatches: 0
      indels: False
      deduplicate: True
      subfolder_name: "all Saka models dist 0 deduplicated"
    - name: "network"
      model_names: [ "Saka_overlap", "Saka_kmer" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 6
      subfolder_name: "all Saka models"
    - name: "precision_recall"
      model_names: [ "Saka_overlap", "Saka_kmer" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 6
      allowed_mismatches: 0
      indels: False
      subfolder_name: "all Saka models dist 0"
    - name: "precision_recall"
      model_names: [ "Saka_overlap", "Saka_kmer" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 6
      allowed_mismatches: 0
      indels: False
      deduplicate: True
      subfolder_name: "all Saka models dist 0 deduplicated"
    - name: "precision_recall"
      model_names: [ "Saka_overlap", "Saka_kmer" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 6
      allowed_mismatches: 1
      indels: True
      subfolder_name: "all Saka models dist 1"
