n_experiments: 7
output_dir: "RESULTS_NOV12/BCR"
input_dir: "data/experimental/collectionB"
seed: 42

sampling:
  - model_name: "VAE_overlap"
    experiment_names: ["exp_0", "exp_1", "exp_2", "exp_3", "exp_4", "exp_5", "exp_6"]
    immuneml_config: "configs/pipelines/experimental_sampling_immuneml.yaml"
    n_samples: 60000
  - model_name: "VAE_kmer"
    experiment_names: ["exp_0", "exp_1", "exp_2", "exp_3", "exp_4", "exp_5", "exp_6"]
    immuneml_config: "configs/pipelines/experimental_sampling_immuneml.yaml"
    n_samples: 60000
