n_experiments: 5
output_dir: "results_mar27/experimental"
input_dir: "data/naive_cd4_clean/"
seed: 42
data_generation:
  experimental: True
  method: "experimental"
  n_samples: 15000
  default_model_name: "humanTRB"
  input_columns: ["junction_aa", "v_call", "j_call"]
models:
    - name: "pwm"
      config: "configs/generative_models/PWM.yaml"
      train_dir: "train"
      test_dir: "test"
    - name: "sonnia"
      config: "configs/generative_models/soNNia.yaml"
      train_dir: "train"
      test_dir: "test"
#    - name: "vae"
#      config: "configs/generative_models/VAE.yaml"
#      train_dir: "train"
#      test_dir: "test"
analyses:
    - name: "network"
      model_names: ["pwm", "sonnia"]
      default_model_name: "humanTRB"
    - name: "novelty"
      model_names: [ "pwm", "sonnia" ]
      default_model_name: "humanTRB"
#    - name: "phenotype"
#      model_names: ["pwm"]
#      default_model_name: "humanTRB"
#    - name: "phenotype"
#      model_names: ["sonnia"]
#      default_model_name: "humanTRB"
#    - name: "phenotype"
#      model_names: [ "vae" ]
#      default_model_name: "humanTRB"