n_experiments: 8
output_dir: "results/experimental"
input_dir: "data"
seed: 42
data_generation:
  experimental: True
  method: "experimental"
  n_samples: 15000
  default_model_name: "humanTRB"
  input_columns: ["junction_aa", "v_call", "j_call"]
models:
    - name: "pwm"
      config: "configs/generative_models/PWM.yaml"
      train_dir: "train"
      test_dir: "test"
    - name: "sonnia"
      config: "configs/generative_models/soNNia.yaml"
      train_dir: "train"
      test_dir: "test"
    - name: "vae"
      config: "configs/generative_models/VAE.yaml"
      train_dir: "train"
      test_dir: "test"
analyses:
    - name: "phenotype"
      model_names: ["pwm"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: ["sonnia"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: [ "vae" ]
      default_model_name: "humanTRB"
    - name: "length_distribution"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "train"
    - name: "length_distribution"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "test"
    - name: "kmer_distribution"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "train"
    - name: "kmer_distribution"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "test"
    - name: "pgen"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
    - name: "aminoacid_distribution"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "train"
    - name: "aminoacid_distribution"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "test"
