n_experiments: 1
output_dir: "RESULTS_TUNING_OCT24/BCR"
input_dir: "data/tuning/BCR"
seed: 42
#data_generation:
#  experimental: True
#  method: "experimental"
#  n_samples: 17500
#  default_model_name: "humanIGH"
#  input_columns: ["junction_aa", "v_call", "j_call", "locus"]

models:
    - name: "S_01"
      immuneml_model_config: "configs/tuning/Saka/S_01.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_02"
      immuneml_model_config: "configs/tuning/Saka/S_02.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_03"
      immuneml_model_config: "configs/tuning/Saka/S_03.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_04"
      immuneml_model_config: "configs/tuning/Saka/S_04.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_05"
      immuneml_model_config: "configs/tuning/Saka/S_05.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_06"
      immuneml_model_config: "configs/tuning/Saka/S_06.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_07"
      immuneml_model_config: "configs/tuning/Saka/S_07.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_08"
      immuneml_model_config: "configs/tuning/Saka/S_08.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_09"
      immuneml_model_config: "configs/tuning/Saka/S_09.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_10"
      immuneml_model_config: "configs/tuning/Saka/S_10.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_11"
      immuneml_model_config: "configs/tuning/Saka/S_11.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_12"
      immuneml_model_config: "configs/tuning/Saka/S_12.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_13"
      immuneml_model_config: "configs/tuning/Saka/S_13.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_14"
      immuneml_model_config: "configs/tuning/Saka/S_14.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_15"
      immuneml_model_config: "configs/tuning/Saka/S_15.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_16"
      immuneml_model_config: "configs/tuning/Saka/S_16.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_17"
      immuneml_model_config: "configs/tuning/Saka/S_17.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_18"
      immuneml_model_config: "configs/tuning/Saka/S_18.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_19"
      immuneml_model_config: "configs/tuning/Saka/S_19.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_20"
      immuneml_model_config: "configs/tuning/Saka/S_20.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_21"
      immuneml_model_config: "configs/tuning/Saka/S_21.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_22"
      immuneml_model_config: "configs/tuning/Saka/S_22.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_23"
      immuneml_model_config: "configs/tuning/Saka/S_23.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_24"
      immuneml_model_config: "configs/tuning/Saka/S_24.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_25"
      immuneml_model_config: "configs/tuning/Saka/S_25.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_26"
      immuneml_model_config: "configs/tuning/Saka/S_26.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_27"
      immuneml_model_config: "configs/tuning/Saka/S_27.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_28"
      immuneml_model_config: "configs/tuning/Saka/S_28.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_29"
      immuneml_model_config: "configs/tuning/Saka/S_29.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_30"
      immuneml_model_config: "configs/tuning/Saka/S_30.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_31"
      immuneml_model_config: "configs/tuning/Saka/S_31.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500
    - name: "S_32"
      immuneml_model_config: "configs/tuning/Saka/S_32.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17500


analyses:
    - name: "reduced_dimensionality"
      model_names: [ "S_01", "S_02", "S_03", "S_04", "S_05", "S_06", "S_07", "S_08",
                     "S_09", "S_10", "S_11", "S_12", "S_13", "S_14", "S_15", "S_16",
                     "S_17", "S_18", "S_19", "S_20", "S_21", "S_22", "S_23", "S_24",
                     "S_25", "S_26", "S_27", "S_28", "S_29", "S_30", "S_31", "S_32" ]
      default_model_name: "humanIGH"
      reference_data: [ "train", "test" ]
      subfolder_name: "all Saka models"
    - name: "memorization"
      model_names: [ "S_01", "S_02", "S_03", "S_04", "S_05", "S_06", "S_07", "S_08",
                     "S_09", "S_10", "S_11", "S_12", "S_13", "S_14", "S_15", "S_16",
                     "S_17", "S_18", "S_19", "S_20", "S_21", "S_22", "S_23", "S_24",
                     "S_25", "S_26", "S_27", "S_28", "S_29", "S_30", "S_31", "S_32" ]
      default_model_name: "humanIGH"
      reference_data: [ "train", "test" ]
      n_subsets: 8
      allowed_mismatches: 0
      indels: False
      subfolder_name: "all Saka models dist 0"
    - name: "diversity"
      model_names: [ "S_01", "S_02", "S_03", "S_04", "S_05", "S_06", "S_07", "S_08",
                     "S_09", "S_10", "S_11", "S_12", "S_13", "S_14", "S_15", "S_16",
                     "S_17", "S_18", "S_19", "S_20", "S_21", "S_22", "S_23", "S_24",
                     "S_25", "S_26", "S_27", "S_28", "S_29", "S_30", "S_31", "S_32" ]
      default_model_name: "humanIGH"
      reference_data: [ "train", "test" ]
      n_subsets: 8
      subfolder_name: "all Saka models"
    - name: "network"
      model_names: [ "S_01", "S_02", "S_03", "S_04", "S_05", "S_06", "S_07", "S_08",
                     "S_09", "S_10", "S_11", "S_12", "S_13", "S_14", "S_15", "S_16",
                     "S_17", "S_18", "S_19", "S_20", "S_21", "S_22", "S_23", "S_24",
                     "S_25", "S_26", "S_27", "S_28", "S_29", "S_30", "S_31", "S_32" ]
      default_model_name: "humanIGH"
      reference_data: [ "train", "test" ]
      n_subsets: 8
      subfolder_name: "all Saka models"
    - name: "precision_recall"
      model_names: [ "S_01", "S_02", "S_03", "S_04", "S_05", "S_06", "S_07", "S_08",
                     "S_09", "S_10", "S_11", "S_12", "S_13", "S_14", "S_15", "S_16",
                     "S_17", "S_18", "S_19", "S_20", "S_21", "S_22", "S_23", "S_24",
                     "S_25", "S_26", "S_27", "S_28", "S_29", "S_30", "S_31", "S_32" ]
      default_model_name: "humanIGH"
      reference_data: [ "train", "test" ]
      n_subsets: 8
      allowed_mismatches: 0
      indels: False
      subfolder_name: "all Saka models dist 0"

tuning:
    - tuning_method: "reduced_dimensionality"
      model_names: [ "S_01", "S_02", "S_03", "S_04", "S_05", "S_06", "S_07", "S_08",
                     "S_09", "S_10", "S_11", "S_12", "S_13", "S_14", "S_15", "S_16",
                     "S_17", "S_18", "S_19", "S_20", "S_21", "S_22", "S_23", "S_24",
                     "S_25", "S_26", "S_27", "S_28", "S_29", "S_30", "S_31", "S_32" ]
      reference_data: [ "train", "test" ]
      subfolder_name: "all Saka models"
      hyperparameter_table_path: "data/hyperparameter_tables/Saka.tsv"
    - tuning_method: "overlap"
      model_names: [ "S_01", "S_02", "S_03", "S_04", "S_05", "S_06", "S_07", "S_08",
                     "S_09", "S_10", "S_11", "S_12", "S_13", "S_14", "S_15", "S_16",
                     "S_17", "S_18", "S_19", "S_20", "S_21", "S_22", "S_23", "S_24",
                     "S_25", "S_26", "S_27", "S_28", "S_29", "S_30", "S_31", "S_32" ]
      reference_data: [ "train", "test" ]
      k_values: [0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 0.5, 0.7, 1.0]
      subfolder_name: "all Saka models dist 0"
      hyperparameter_table_path: "data/hyperparameter_tables/Saka.tsv"
