n_experiments: 9
output_dir: "results/covid_igh_igk_igl/"
input_dir: "data/covid_igh_igk_igl/"
seed: 42
data_generation:
  experimental: True
  method: "experimental"
  n_samples: 22000
  default_model_name: "humanTRB"
  input_columns: ["junction_aa", "v_call", "j_call"]
models:
    - name: "pwm"
      config: "configs/generative_models/PWM.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 22000
    - name: "sonnia"
      config: "configs/generative_models/soNNia.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 22000
    - name: "vae"
      config: "configs/generative_models/VAE.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 17000
analyses:
    - name: "precision_recall"
      model_names: [ "vae" ]
      default_model_name: "humanTRB"
      reference_data: "test"
      n_subsets: 50
    - name: "network"
      model_names: ["vae"]
      default_model_name: "humanTRB"
      reference_data: "train"
      n_subsets: 50
    - name: "network"
      model_names: [ "vae" ]
      default_model_name: "humanTRB"
      reference_data: "test"
      n_subsets: 50
    - name: "novelty"
      model_names: [ "pwm", "sonnia" ]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: ["pwm"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: ["sonnia"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: [ "vae" ]
      default_model_name: "humanTRB"
