n_experiments: 1
output_dir: "results_dummy/experimental_tuning"
input_dir: "data/experimental/dummy"
seed: 42
data_generation:
  experimental: True
  method: "experimental"
  n_samples: 100
  default_model_name: "humanTRB"
  input_columns: ["junction_aa", "v_call", "j_call", "locus" ]

models:
    - name: "vae"
      immuneml_model_config: "configs/dummy_generative_models/SimpleVAE.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 100
    - name: "pwm"
      immuneml_model_config: "configs/dummy_generative_models/PWM.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 100

analyses:
    - name: "memorization"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 10
    - name: "reduced_dimensionality"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
    - name: "precision_recall"
      model_names: [ "pwm", "vae" ]
      default_model_name: "humanTRB"
      reference_data: [ "train", "test" ]
      n_subsets: 10

tuning:
    - tuning_method: "reduced_dimensionality"
      model_names: [ "pwm", "vae" ]
      reference_data: [ "train", "test" ]
    - tuning_method: "overlap"
      model_names: [ "pwm", "vae" ]
      reference_data: [ "train", "test" ]
      k_values: [0.001, 0.005, 0.01, 0.05, 0.1, 0.3, 0.5, 0.7, 1.0]
