n_experiments: 3
output_dir: "results_dummy_july18_2/covid_igh_igk_igl"
input_dir: "data/covid_igh_igk_igl"
seed: 42
data_generation:
  experimental: True
  method: "experimental_umi"
  n_samples: 1000
  default_model_name: "humanIGH"
  input_columns: ["junction_aa", "v_call", "j_call", "umi_count", "locus" ]
models:
#    - name: "vae"
#      config: "configs/dummy_generative_models/SimpleVAE.yaml"
#      train_dir: "train"
#      test_dir: "test"
#      n_subset_samples: 100
    - name: "pwm"
      config: "configs/dummy_generative_models/PWM.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 100
#    - name: "sonnia"
#      config: "configs/dummy_generative_models/SoNNia.yaml"
#      train_dir: "train"
#      test_dir: "test"
#      n_subset_samples: 100
    - name: "lstm"
      config: "configs/dummy_generative_models/SimpleLSTM.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 100
analyses:
    - name: "precision_recall"
      model_names: [ "pwm", "lstm" ]
      default_model_name: "humanTRB"
      reference_data: "test"
      n_subsets: 10
    - name: "diversity"
      model_names: [ "pwm", "lstm" ]
      default_model_name: "humanTRB"
      reference_data: "test"
      n_subsets: 10
#    - name: "novelty"
#      model_names: ["pwm", "sonnia", "vae"]
#      default_model_name: "humanTRB"
#    - name: "phenotype"
#      model_names: ["pwm"]
#      default_model_name: "humanTRB"
#    - name: "phenotype"
#      model_names: ["sonnia"]
#      default_model_name: "humanTRB"
#    - name: "phenotype"
#      model_names: [ "vae" ]
#      default_model_name: "humanTRB"
#    - name: "reduced_dimensionality"
#      model_names: [ "pwm", "sonnia", "vae" ]
#      default_model_name: "humanTRB"
#      reference_data: "train"
#    - name: "reduced_dimensionality"
#      model_names: [ "pwm", "sonnia", "vae" ]
#      default_model_name: "humanTRB"
#      reference_data: "test"
#    - name: "pgen"
#      model_names: [ "pwm", "sonnia", "vae" ]
#      default_model_name: "humanTRB"
#    - name: "network"
#      model_names: [ "pwm", "sonnia", "vae" ]
#      default_model_name: "humanTRB"
#      reference_data: "train"
#      n_subsets: 20
#    - name: "network"
#      model_names: [ "pwm", "sonnia", "vae" ]
#      default_model_name: "humanTRB"
#      reference_data: "test"
#      n_subsets: 20
