n_experiments: 2
output_dir: "results_dummy/experimental"
input_dir: "data/experimental/dummy/"
seed: 42
data_generation:
  experimental: True
  method: "experimental"
  n_samples: 20
  default_model_name: "humanTRB"
  input_columns: ["junction_aa", "v_call", "j_call"]
models:
    - name: "pwm"
      config: "configs/dummy_generative_models/PWM.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 10
    - name: "sonnia"
      config: "configs/dummy_generative_models/SoNNia.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 10
    - name: "vae"
      config: "configs/dummy_generative_models/VAE.yaml"
      train_dir: "train"
      test_dir: "test"
      n_subset_samples: 10
analyses:
    - name: "novelty"
      model_names: ["pwm", "sonnia", "vae"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: ["pwm"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: ["sonnia"]
      default_model_name: "humanTRB"
    - name: "phenotype"
      model_names: [ "vae" ]
      default_model_name: "humanTRB"
    - name: "reduced_dimensionality"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "train"
    - name: "reduced_dimensionality"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "test"
    - name: "pgen"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
    - name: "network"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "train"
      n_subsets: 20
    - name: "network"
      model_names: [ "pwm", "sonnia", "vae" ]
      default_model_name: "humanTRB"
      reference_data: "test"
      n_subsets: 20
