definitions:
  datasets:
    dataset:
      format: AIRR
      params:
        path: data.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_JUNCTION
        separator: "\t"
  ml_methods:
    model:
      SimpleVAE:
        batch_size: 512
        beta: 0.75
        cdr3_embed_dim: 21
        locus: beta
        device: cpu
        j_gene_embed_dim: 13
        latent_dim: 30
        linear_nodes_count: 256
        num_epochs: 1000
        patience: 20
        pretrains: 5
        v_gene_embed_dim: 30
        warmup_epochs: 20
        validation_split: 0.1
instructions:
  gen_model:
    type: TrainGenModel
    export_combined_dataset: False
    dataset: dataset
    method: model
    gen_examples_count: 140000
    number_of_processes: 1
