definitions:
  datasets:
    dataset:
      format: AIRR
      params:
        path: data.tsv
        is_repertoire: False
        paired: False
        region_type: IMGT_JUNCTION
        separator: "\t"
  ml_methods:
    model:
      SimpleVAE:
        batch_size: 100
        beta: 0.75
        cdr3_embed_dim: 21
        locus: beta
        device: cpu
        j_gene_embed_dim: 13
        latent_dim: 20
        linear_nodes_count: 75
        num_epochs: 1
        patience: 1
        pretrains: 1
        v_gene_embed_dim: 30
        warmup_epochs: 1
        validation_split: 0.1

instructions:
  gen_model:
    type: TrainGenModel
    export_combined_dataset: True
    dataset: dataset
    method: model
    gen_examples_count: 1000
    number_of_processes: 1
