""" Repertoire-level statistics shared by the analyses.

The unit of analysis is the repertoire, not the generated subset: subsets generated by the same fitted model are not
independent observations, so their scores are first averaged within each repertoire. Models are then summarised and
compared across repertoires, pairing the scores of two sources (two models, or a model and the train vs. test
reference) on the same repertoire.

There are two modes, set per analysis with statistical_tests:

- Descriptive (default): for collections with several repertoires per donor (different tissues, cell subsets or
  chains), where repertoires are not independent. Models are summarised with the mean and standard deviation across
  repertoires, and comparisons with the mean difference and the number of repertoires and donors in which the first
  source is lower or higher. No confidence intervals or p-values are computed.
- Statistical tests: for collections with one repertoire per donor, where repertoires are independent. In addition,
  t-based confidence intervals are computed for the means and mean differences, and each comparison is tested with a
  two-sided paired sign-flip permutation test: under the null hypothesis of no difference, the sign of each
  repertoire's difference is equally likely to be positive or negative, so the observed mean difference is compared
  to the mean differences of all sign combinations (exactly for up to MAX_EXACT_REPERTOIRES repertoires, otherwise by
  Monte Carlo). Every set of comparisons (with the train vs. test reference, the contrasts from the config, all
  pairs of models) is a separate multiple testing family, corrected with Holm, which controls the probability of any
  false positive in the family (family-wise error rate).

Donors are derived from the repertoire names with donor_pattern, a regular expression whose first group (or whole
match) is the donor, e.g. "^([^_]+)_" for 6271_pLN_CD8. Without a pattern, every repertoire is its own donor.
"""
import os
import re
from itertools import combinations

import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.multitest import multipletests

CONFIDENCE_LEVEL = 0.95
ALPHA = 0.05
MAX_EXACT_REPERTOIRES = 20
N_PERMUTATIONS = 100_000
PERMUTATION_SEED = 42
PERMUTATION_CHUNK_SIZE = 2 ** 16
CORRECTION = "holm"
TRAIN_TEST_REFERENCE = "train vs. test"

DESCRIPTIVE_COMPARISON_COLUMNS = ["first", "second", "n_repertoires", "n_donors", "mean_difference", "sd_difference",
                                  "n_first_higher", "n_first_lower", "n_donors_first_higher",
                                  "n_donors_first_lower"]
TEST_COMPARISON_COLUMNS = DESCRIPTIVE_COMPARISON_COLUMNS + ["ci_low", "ci_high", "p_value", "p_adjusted",
                                                            "correction", "test", "min_possible_p"]


def get_donor(repertoire: str, donor_pattern: str | None) -> str:
    """ Returns the donor of a repertoire: the first group (or the whole match) of donor_pattern in the repertoire
    name, or the repertoire itself if there is no pattern. """
    if donor_pattern is None:
        return repertoire
    match = re.search(donor_pattern, repertoire)
    if match is None:
        raise ValueError(f"The donor pattern {donor_pattern} does not match the repertoire {repertoire}.")
    return match.group(1) if match.groups() else match.group(0)


def aggregate_repertoire_scores(scores_df: pd.DataFrame, score_column: str, donor_pattern: str | None = None,
                                source_column: str = "model", repertoire_column: str = "dataset") -> pd.DataFrame:
    """ Averages the scores of the generated subsets within each repertoire.
    Args:
        scores_df (pd.DataFrame): One row per source, repertoire and generated subset.
        score_column (str): Column with the scores.
        donor_pattern (str | None): Regular expression that extracts the donor from the repertoire name.
        source_column (str): Column with the source of the scores, usually the model name.
        repertoire_column (str): Column with the repertoire the scores belong to.
    Returns:
        pd.DataFrame: Columns source, repertoire, donor, score and n_subsets, one row per source and repertoire.
    """
    grouped = scores_df.groupby([source_column, repertoire_column])[score_column]
    repertoire_scores = grouped.agg(score="mean", n_subsets="count").reset_index()
    repertoire_scores = repertoire_scores.rename(columns={source_column: "source", repertoire_column: "repertoire"})
    repertoire_scores.insert(2, "donor", [get_donor(repertoire, donor_pattern)
                                          for repertoire in repertoire_scores["repertoire"]])
    return repertoire_scores


def check_one_repertoire_per_donor(repertoire_scores: pd.DataFrame) -> None:
    """ Raises an error if a donor has several repertoires, since the statistical tests assume that the repertoires
    are independent. """
    n_repertoires = repertoire_scores.groupby("donor")["repertoire"].nunique()
    repeated_donors = n_repertoires[n_repertoires > 1].index.tolist()
    if repeated_donors:
        raise ValueError(f"Statistical tests assume one repertoire per donor, but donors {repeated_donors} have "
                         f"several repertoires. Set statistical_tests to False for this collection.")


def t_confidence_interval(values) -> tuple[float, float]:
    """ Returns the t-based confidence interval for the mean of the values, or nan if there are fewer than two. """
    values = np.asarray(values, dtype=float)
    values = values[~np.isnan(values)]
    if len(values) < 2:
        return np.nan, np.nan
    half_width = (stats.t.ppf((1 + CONFIDENCE_LEVEL) / 2, len(values) - 1)
                  * values.std(ddof=1) / np.sqrt(len(values)))
    return values.mean() - half_width, values.mean() + half_width


def summarise_repertoire_scores(repertoire_scores: pd.DataFrame, statistical_tests: bool) -> pd.DataFrame:
    """ Summarises the repertoire scores of each source with the mean and standard deviation, and with the
    confidence interval if statistical tests are used.
    Args:
        repertoire_scores (pd.DataFrame): Scores as returned by aggregate_repertoire_scores.
        statistical_tests (bool): Whether the repertoires are independent, so that confidence intervals apply.
    Returns:
        pd.DataFrame: One row per source with n_repertoires, n_donors, mean, sd and, with statistical tests, ci_low
        and ci_high.
    """
    rows = []
    for source, group in repertoire_scores.groupby("source", sort=False):
        group = group.dropna(subset=["score"])
        row = {"source": source,
               "n_repertoires": len(group),
               "n_donors": group["donor"].nunique(),
               "mean": group["score"].mean() if len(group) else np.nan,
               "sd": group["score"].std(ddof=1) if len(group) > 1 else np.nan}
        if statistical_tests:
            row["ci_low"], row["ci_high"] = t_confidence_interval(group["score"])
        rows.append(row)
    columns = ["source", "n_repertoires", "n_donors", "mean", "sd"] + (["ci_low", "ci_high"]
                                                                      if statistical_tests else [])
    return pd.DataFrame(rows, columns=columns)


def sign_flip_test(differences) -> tuple[float, str]:
    """ Two-sided paired sign-flip permutation test of whether the mean difference is zero.
    Args:
        differences: The per-repertoire differences between two sources.
    Returns:
        tuple[float, str]: The p-value and a description of how it was computed.
    """
    differences = np.asarray(differences, dtype=float)
    n = len(differences)
    if n == 0:
        return np.nan, "none"
    observed = abs(differences.mean())
    # Tolerance so that sign combinations with the same mean as the observed one count as at least as extreme
    threshold = observed - 1e-12 * max(observed, 1.0)

    if n <= MAX_EXACT_REPERTOIRES:
        n_combinations = 2 ** n
        bits = np.arange(n)
        n_extreme = 0
        for start in range(0, n_combinations, PERMUTATION_CHUNK_SIZE):
            indices = np.arange(start, min(start + PERMUTATION_CHUNK_SIZE, n_combinations))
            signs = 1 - 2 * ((indices[:, None] >> bits) & 1)
            n_extreme += np.count_nonzero(np.abs(signs @ differences) / n >= threshold)
        return n_extreme / n_combinations, "exact sign-flip"

    rng = np.random.default_rng(PERMUTATION_SEED)
    n_extreme = 0
    for start in range(0, N_PERMUTATIONS, PERMUTATION_CHUNK_SIZE):
        size = min(PERMUTATION_CHUNK_SIZE, N_PERMUTATIONS - start)
        signs = rng.choice([-1, 1], size=(size, n))
        n_extreme += np.count_nonzero(np.abs(signs @ differences) / n >= threshold)
    return (n_extreme + 1) / (N_PERMUTATIONS + 1), f"Monte Carlo sign-flip ({N_PERMUTATIONS} permutations)"


def min_possible_p(n_repertoires: int) -> float:
    """ The smallest p-value the sign-flip test can give for this number of repertoires, reached when all
    differences have the same sign. """
    if n_repertoires == 0:
        return np.nan
    if n_repertoires <= MAX_EXACT_REPERTOIRES:
        return 2 / 2 ** n_repertoires
    return 1 / (N_PERMUTATIONS + 1)


def compare_paired(repertoire_scores: pd.DataFrame, comparisons: list,
                   statistical_tests: bool) -> tuple[pd.DataFrame, pd.DataFrame]:
    """ Compares pairs of sources on the repertoires they share, as first minus second.
    Args:
        repertoire_scores (pd.DataFrame): Scores as returned by aggregate_repertoire_scores.
        comparisons (list): Pairs (first, second) of sources to compare. They form one multiple testing family.
        statistical_tests (bool): Whether to add confidence intervals and tests, Holm-corrected across the
            comparisons.
    Returns:
        tuple[pd.DataFrame, pd.DataFrame]: One row per comparison with the mean difference and the number of
        repertoires and donors in which the first source is higher and lower (a donor counts by the mean difference
        over its repertoires), plus confidence intervals and p-values with statistical tests; and the
        per-repertoire differences.
    """
    scores = repertoire_scores.pivot(index="repertoire", columns="source", values="score")
    donors = repertoire_scores.drop_duplicates("repertoire").set_index("repertoire")["donor"]
    rows, differences_dfs = [], []
    for first, second in comparisons:
        paired = scores[[first, second]].dropna()
        differences = (paired[first] - paired[second]).rename("difference").reset_index()
        differences.insert(1, "donor", differences["repertoire"].map(donors))
        donor_differences = differences.groupby("donor")["difference"].mean()
        values = differences["difference"].to_numpy()
        row = {"first": first,
               "second": second,
               "n_repertoires": len(values),
               "n_donors": len(donor_differences),
               "mean_difference": values.mean() if len(values) else np.nan,
               "sd_difference": values.std(ddof=1) if len(values) > 1 else np.nan,
               "n_first_higher": int((values > 0).sum()),
               "n_first_lower": int((values < 0).sum()),
               "n_donors_first_higher": int((donor_differences > 0).sum()),
               "n_donors_first_lower": int((donor_differences < 0).sum())}
        if statistical_tests:
            row["ci_low"], row["ci_high"] = t_confidence_interval(values)
            row["p_value"], row["test"] = sign_flip_test(values)
            row["p_adjusted"], row["correction"] = np.nan, CORRECTION
            row["min_possible_p"] = min_possible_p(len(values))
        rows.append(row)
        differences_dfs.append(differences.assign(first=first, second=second))

    comparisons_df = pd.DataFrame(rows, columns=TEST_COMPARISON_COLUMNS if statistical_tests
                                  else DESCRIPTIVE_COMPARISON_COLUMNS)
    if statistical_tests:
        tested = comparisons_df["p_value"].notna()
        if tested.any():
            comparisons_df.loc[tested, "p_adjusted"] = multipletests(comparisons_df.loc[tested, "p_value"],
                                                                     alpha=ALPHA, method=CORRECTION)[1]
    differences_df = (pd.concat(differences_dfs, ignore_index=True) if differences_dfs
                      else pd.DataFrame(columns=["repertoire", "donor", "difference"]))
    differences_df = differences_df.reindex(columns=["first", "second", "repertoire", "donor", "difference"])
    return comparisons_df, differences_df


def is_underpowered(comparisons_df: pd.DataFrame) -> bool:
    """ Whether no comparison of a Holm-corrected family can reach significance, even if every repertoire showed a
    difference in the same direction. Holm can only reject anything if the smallest p-value is at most alpha divided
    by the number of comparisons. """
    if comparisons_df.empty or "min_possible_p" not in comparisons_df:
        return False
    return comparisons_df["min_possible_p"].min() * len(comparisons_df) > ALPHA


def validate_contrasts(contrasts: list, sources: list) -> list:
    """ Checks that the contrasts from the config are pairs of known sources and returns them as tuples. """
    validated = []
    for contrast in contrasts:
        if len(contrast) != 2:
            raise ValueError(f"Contrasts must be pairs of model names, got {contrast}.")
        unknown = [source for source in contrast if source not in sources]
        if unknown:
            raise ValueError(f"Unknown models in contrast {contrast}: {unknown}. Known models: {sources}.")
        validated.append(tuple(contrast))
    return validated


def describe_error_bars(statistical_tests: bool, n_repertoires: int, n_donors: int) -> str:
    """ Returns the caption that explains the error bars of a plot. """
    sample = f"n={n_repertoires}" if n_repertoires == n_donors else f"n={n_repertoires} from {n_donors} donors"
    if statistical_tests:
        return f"Error bars: {CONFIDENCE_LEVEL:.0%} CI across repertoires ({sample}); dots: repertoires"
    return f"Error bars: SD across repertoires ({sample}); dots: repertoires"


def run_repertoire_statistics(repertoire_scores: pd.DataFrame, models: list, output_prefix: str,
                              statistical_tests: bool, reference_scores: pd.DataFrame = None,
                              contrasts: list = None, donor_pattern: str | None = None) -> dict:
    """ Summarises and compares the models for one metric and writes the results to tsv files.
    Args:
        repertoire_scores (pd.DataFrame): Model scores as returned by aggregate_repertoire_scores.
        models (list): The models to compare, in plotting order.
        output_prefix (str): Path prefix of the output files.
        statistical_tests (bool): Whether to compute confidence intervals and tests. Requires one repertoire per
            donor.
        reference_scores (pd.DataFrame): Optional train vs. test scores per repertoire, with columns repertoire and
            score. Every model is compared to them.
        contrasts (list): Optional pre-specified pairs of models to compare, e.g. from the analysis config.
        donor_pattern (str | None): Regular expression that extracts the donor from the repertoire name.
    Returns:
        dict: The summary table, and for each set of comparisons ("vs_train_test", "contrasts", "all_pairs") the
        comparisons table and the per-repertoire differences (keyed by the set name plus "_differences").
    """
    os.makedirs(os.path.dirname(output_prefix), exist_ok=True)
    models = [model for model in models if model in set(repertoire_scores["source"])]
    scores = repertoire_scores[repertoire_scores["source"].isin(models)]
    if statistical_tests:
        check_one_repertoire_per_donor(scores)
    if reference_scores is not None:
        reference_scores = reference_scores.assign(
            source=TRAIN_TEST_REFERENCE,
            donor=[get_donor(repertoire, donor_pattern) for repertoire in reference_scores["repertoire"]])
        scores = pd.concat([scores, reference_scores], ignore_index=True)

    comparison_sets = {}
    if reference_scores is not None:
        comparison_sets["vs_train_test"] = [(model, TRAIN_TEST_REFERENCE) for model in models]
    if contrasts:
        comparison_sets["contrasts"] = validate_contrasts(contrasts, models)
    comparison_sets["all_pairs"] = list(combinations(models, 2))

    results = {"summary": summarise_repertoire_scores(scores, statistical_tests)}
    for name, comparisons in comparison_sets.items():
        results[name], results[f"{name}_differences"] = compare_paired(scores, comparisons, statistical_tests)

    scores.to_csv(f"{output_prefix}_repertoire_scores.tsv", sep="\t", index=False)
    for name, table in results.items():
        table.to_csv(f"{output_prefix}_{name}.tsv", sep="\t", index=False)
        if is_underpowered(table):
            print(f"Warning: with {table['n_repertoires'].max()} repertoires and {len(table)} Holm-corrected "
                  f"comparisons, none of the comparisons in {output_prefix}_{name}.tsv can reach significance at "
                  f"alpha={ALPHA}.")
    return results
